config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :photos, only: %i[index show]
  resources :photographers, only: %i[index show]
  resources :about, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :photographer
  validates :photographer, :width, :height, :url, :download_url, presence: true
  validates :url, :download_url, uniqueness: true
  validates :width, :height, numericality: { only_integer: true }
end

app/models/photographer.rb
class Photographer < ApplicationRecord
  has_many :photos
  validates :photographer, presence: true, uniqueness: true

  def self.search(search)
    if search
      photographer = Photographer.find_by(photographer: search)
      if photographer
        where(id: photographer)
      else
        Photographer.all
      end
    else
      Photographer.all
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @photo = Photo.first
    @photographer = Photographer.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @photo = Photo.includes(:photographer).first
  end
end

app/controllers/photographers_controller.rb
class PhotographersController < ApplicationController
  def index
    @photographers = Photographer.search(params[:search]).page(params[:page]).all
  end

  def show
    @photographer = Photographer.find(params[:id])
    @photos = Photo.where(photographer: @photographer.id).all
  end

  def photograper_params
    params.require(:photographer).permit(:photographer, :search)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.includes(:photographer).page(params[:page]).all
  end

  def show
    @photo = Photo.find(params[:id])
    @photographer = Photographer.find(@photo.photographer.id)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photographers_helper.rb
module PhotographersHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/about/index.html.erb
<h2 class="title">About this Web Application</h2>

<h3 class="subtitle mt-5">ERD Looks Like</h3>
<img src="ProjectERD.png" alt="Website ERD"/>

<h4 class="subtitle mb-3">Data for Photos looks like</h4>

<p>
  <strong>ID:</strong>
  <%= @photo.id %>
</p>

<p>
  <strong>Photographer(Reference):</strong>
  <%= @photo.photographer.photographer %>
</p>

<p>
  <strong>Width:</strong>
  <%= @photo.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @photo.height %>
</p>

<p>
  <strong>Url:</strong>
  <%= @photo.url %>
</p>

<p>
  <strong>Download_url:</strong>
  <%= @photo.download_url %>
</p>

<br>

<h4 class="subtitle mb-3">Data for Photographers looks like</h4>

<p>
  <strong>ID:</strong>
  <%= @photographer.id %>
</p>

<p>
  <strong>Photographer:</strong>
  <%= @photographer.photographer %>
</p>

app/views/home/index.html.erb
<h2 class="title">A basic Photography website by, Branden Carpick</h2>
<h3 class="subtitle">Images courtesy of Unsplash via Lorem Picsum</h3>

<img src="<%= @photo.download_url %>" width="500" height="500" alt="A picture">
<p>
  <strong>Image by:</strong>
  <%= @photo.photographer.photographer %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= yield(:html_title) + " - " if content_for?(:html_title) %>Photography by Unsplash & Picsum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="has-navbar-fixed-top">
    <nav class="navbar is-fixed-top is-danger" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" >
          <img src="https://bulma.io/images/bulma-logo.png" alt="Bulma: Free, open source, and modern CSS framework based on Flexbox" width="112" height="28">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div class="navbar-start">
        <a class="navbar-item" href="/">
          Home
        </a>

        <a class="navbar-item" href="/photos">
          Photos
        </a>

        <a class="navbar-item" href="/photographers">
          Photographers
        </a>

        <a class="navbar-item" href="/about">
          About
        </a>
      </div>
    </nav>
    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
  </body>
</html>

app/views/photographers/index.html.erb
<h2 class="title">Photographers</h2>

<h3 class="subtitle mt-5 mb-3">Search by Name: </h3>
<%= form_tag(photographers_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag ("Search") %>
<% end %>

<br>

<%= paginate @photographers %>

<table class="table is-striped is-fullwidth is-bordered">
  <thead>
    <tr>
      <th><abbr title="Photographer ID">Link</abbr></th>
      <th><abbr>Photographer</abbr></th>
    </tr>
  </thead>
  <tbody>
    <% @photographers.each do |photographer| %>
      <tr>
        <th><%= link_to photographer.id, photographer %></th>
        <td><%= photographer.photographer %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @photographers %>

app/views/photographers/show.html.erb
<% content_for(:html_title) { @photographer.photographer } %>

<h2 class="title">Photographer <%= @photographer.photographer %></h2>

<h2 class="subtitle mt-5 mb-3">Photos:</h2>
<ul>
  <% @photos.each do |photo| %>
    <li><%= link_to photo.id, photo %></li>
  <% end %>
</ul>

app/views/photos/index.html.erb
<h2 class="title">Photos</h2>

<%= paginate @photos %>
<table class="table is-striped is-fullwidth is-bordered">
  <thead>
    <tr>
      <th><abbr title="Photo ID">Link</abbr></th>
      <th><abbr>Photographer</abbr></th>
    </tr>
  </thead>
  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <th><%= link_to photo.id, photo %></th>
        <td><%= photo.photographer.photographer %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @photos %>

app/views/photos/show.html.erb
<% content_for(:html_title) { @photographer.photographer } %>

<h2 class="title">Photo by <%= link_to @photo.photographer.photographer, @photographer %></h2>

<img src="<%= @photo.download_url %>" width="500" height="500" alt="A picture">

<h2 class="subtitle mt-5 mb-3">Photo Details:</h2>

<p>
  <strong>Width:</strong>
  <%= @photo.width%>
</p>

<p>
  <strong>Height:</strong>
  <%= @photo.height%>
</p>

<p>
  <strong>URL:</strong>
  <a href="<%= @photo.url %>">Click Here!</a>
</p>

<p>
  <strong>Download URL:</strong>
  <a href="<%= @photo.download_url %>">Click Here!</a>
</p>